# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Node.js App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 15.x

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      working-directory: codebase/rdicidr-0.1.0
      run: npm ci

    - name: Run Lint
      working-directory: codebase/rdicidr-0.1.0
      run: npm run lint

    - name: Run Prettier
      working-directory: codebase/rdicidr-0.1.0
      run: npm run prettier

    - name: Run tests
      working-directory: codebase/rdicidr-0.1.0
      env:
        CI: 'true'
      run: npm test

    - name: Bulid Node.js App
      working-directory: codebase/rdicidr-0.1.0
      run: npm run build
